<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Besm6.BitVisualizer.WinForms</RootNamespace>
    <AssemblyTitle>Визуализатор чисел и команд БЭСМ-6</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Besm6.Architecture\Besm6.Architecture.csproj" />
    <ProjectReference Include="..\Besm6.BitVisualizer\Besm6.BitVisualizer.csproj" />
  </ItemGroup>

</Project>