<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
    <PackageReference Include="MSTest" Version="4.0.2" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.2.3" />
    <PackageReference Include="MSTest.TestFramework" Version="4.2.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
    <Using Include="Besm6.Architecture" />
    <Using Include="Besm6.Runtime" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Besm6.Architecture\Besm6.Architecture.csproj" />
    <ProjectReference Include="..\..\src\Besm6.Processor\Besm6.Processor.csproj" />
    <ProjectReference Include="..\..\src\Besm6.Assembler\Besm6.Assembler.csproj" />
    <ProjectReference Include="..\..\src\Besm6.Runtime\Besm6.Runtime.csproj" />
    <ProjectReference Include="..\..\src\Besm6.Cli\Besm6.Cli.csproj" />
    <ProjectReference Include="..\..\src\Besm6.Tui\Besm6.Tui.csproj" />
  </ItemGroup>

</Project>
